//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 07:41:16 AM EST 
//


package aero.aixm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApproachAltitudeTablePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApproachAltitudeTablePropertyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1}AbstractAIXMPropertyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.aixm.aero/schema/5.1}ApproachAltitudeTable"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApproachAltitudeTablePropertyType", propOrder = {
    "approachAltitudeTable"
})
public class ApproachAltitudeTablePropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "ApproachAltitudeTable", required = true)
    protected ApproachAltitudeTableType approachAltitudeTable;

    /**
     * Gets the value of the approachAltitudeTable property.
     * 
     * @return
     *     possible object is
     *     {@link ApproachAltitudeTableType }
     *     
     */
    public ApproachAltitudeTableType getApproachAltitudeTable() {
        return approachAltitudeTable;
    }

    /**
     * Sets the value of the approachAltitudeTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproachAltitudeTableType }
     *     
     */
    public void setApproachAltitudeTable(ApproachAltitudeTableType value) {
        this.approachAltitudeTable = value;
    }

    public boolean isSetApproachAltitudeTable() {
        return (this.approachAltitudeTable!= null);
    }

}
