//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 07:41:16 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aixm.aero/schema/5.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package aero.aixm;
