//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 07:41:16 AM EST 
//


package aero.aixm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerticalStructureTimeSliceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerticalStructureTimeSliceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1}AbstractAIXMTimeSliceType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.aixm.aero/schema/5.1}VerticalStructurePropertyGroup"/>
 *         &lt;element name="extension" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.aixm.aero/schema/5.1}AbstractVerticalStructureExtension"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalStructureTimeSliceType", propOrder = {
    "aixmName",
    "type",
    "lighted",
    "markingICAOStandard",
    "group",
    "length",
    "width",
    "radius",
    "lightingICAOStandard",
    "synchronisedLighting",
    "marker",
    "part",
    "hostedPassengerService",
    "supportedGroundLight",
    "hostedNavaidEquipment",
    "hostedSpecialNavStation",
    "hostedUnit",
    "hostedOrganisation",
    "supportedService",
    "annotation",
    "lightingAvailability",
    "extension"
})
public class VerticalStructureTimeSliceType
    extends AbstractAIXMTimeSliceType
{

    @XmlElementRef(name = "name", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<TextNameType> aixmName;
    @XmlElementRef(name = "type", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeVerticalStructureType> type;
    @XmlElementRef(name = "lighted", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeYesNoType> lighted;
    @XmlElementRef(name = "markingICAOStandard", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeYesNoType> markingICAOStandard;
    @XmlElementRef(name = "group", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeYesNoType> group;
    @XmlElementRef(name = "length", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<ValDistanceType> length;
    @XmlElementRef(name = "width", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<ValDistanceType> width;
    @XmlElementRef(name = "radius", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<ValDistanceType> radius;
    @XmlElementRef(name = "lightingICAOStandard", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeYesNoType> lightingICAOStandard;
    @XmlElementRef(name = "synchronisedLighting", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeYesNoType> synchronisedLighting;
    @XmlElementRef(name = "marker", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class, required = false)
    protected JAXBElement<MarkerBeaconPropertyType> marker;
    @XmlElement(nillable = true)
    protected List<VerticalStructurePartPropertyType> part;
    @XmlElement(nillable = true)
    protected List<PassengerServicePropertyType> hostedPassengerService;
    @XmlElement(nillable = true)
    protected List<GroundLightSystemPropertyType> supportedGroundLight;
    @XmlElement(nillable = true)
    protected List<NavaidEquipmentPropertyType> hostedNavaidEquipment;
    @XmlElement(nillable = true)
    protected List<SpecialNavigationStationPropertyType> hostedSpecialNavStation;
    @XmlElement(nillable = true)
    protected List<UnitPropertyType> hostedUnit;
    @XmlElement(nillable = true)
    protected List<OrganisationAuthorityPropertyType> hostedOrganisation;
    @XmlElement(nillable = true)
    protected List<ServicePropertyType> supportedService;
    @XmlElement(nillable = true)
    protected List<NotePropertyType> annotation;
    @XmlElement(nillable = true)
    protected List<VerticalStructureLightingStatusPropertyType> lightingAvailability;
    protected List<VerticalStructureTimeSliceType.Extension> extension;

    /**
     * Gets the value of the aixmName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextNameType }{@code >}
     *     
     */
    public JAXBElement<TextNameType> getAIXMName() {
        return aixmName;
    }

    /**
     * Sets the value of the aixmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextNameType }{@code >}
     *     
     */
    public void setAIXMName(JAXBElement<TextNameType> value) {
        this.aixmName = value;
    }

    public boolean isSetAIXMName() {
        return (this.aixmName!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeVerticalStructureType }{@code >}
     *     
     */
    public JAXBElement<CodeVerticalStructureType> getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeVerticalStructureType }{@code >}
     *     
     */
    public void setType(JAXBElement<CodeVerticalStructureType> value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the lighted property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public JAXBElement<CodeYesNoType> getLighted() {
        return lighted;
    }

    /**
     * Sets the value of the lighted property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public void setLighted(JAXBElement<CodeYesNoType> value) {
        this.lighted = value;
    }

    public boolean isSetLighted() {
        return (this.lighted!= null);
    }

    /**
     * Gets the value of the markingICAOStandard property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public JAXBElement<CodeYesNoType> getMarkingICAOStandard() {
        return markingICAOStandard;
    }

    /**
     * Sets the value of the markingICAOStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public void setMarkingICAOStandard(JAXBElement<CodeYesNoType> value) {
        this.markingICAOStandard = value;
    }

    public boolean isSetMarkingICAOStandard() {
        return (this.markingICAOStandard!= null);
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public JAXBElement<CodeYesNoType> getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public void setGroup(JAXBElement<CodeYesNoType> value) {
        this.group = value;
    }

    public boolean isSetGroup() {
        return (this.group!= null);
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValDistanceType }{@code >}
     *     
     */
    public JAXBElement<ValDistanceType> getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValDistanceType }{@code >}
     *     
     */
    public void setLength(JAXBElement<ValDistanceType> value) {
        this.length = value;
    }

    public boolean isSetLength() {
        return (this.length!= null);
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValDistanceType }{@code >}
     *     
     */
    public JAXBElement<ValDistanceType> getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValDistanceType }{@code >}
     *     
     */
    public void setWidth(JAXBElement<ValDistanceType> value) {
        this.width = value;
    }

    public boolean isSetWidth() {
        return (this.width!= null);
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValDistanceType }{@code >}
     *     
     */
    public JAXBElement<ValDistanceType> getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValDistanceType }{@code >}
     *     
     */
    public void setRadius(JAXBElement<ValDistanceType> value) {
        this.radius = value;
    }

    public boolean isSetRadius() {
        return (this.radius!= null);
    }

    /**
     * Gets the value of the lightingICAOStandard property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public JAXBElement<CodeYesNoType> getLightingICAOStandard() {
        return lightingICAOStandard;
    }

    /**
     * Sets the value of the lightingICAOStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public void setLightingICAOStandard(JAXBElement<CodeYesNoType> value) {
        this.lightingICAOStandard = value;
    }

    public boolean isSetLightingICAOStandard() {
        return (this.lightingICAOStandard!= null);
    }

    /**
     * Gets the value of the synchronisedLighting property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public JAXBElement<CodeYesNoType> getSynchronisedLighting() {
        return synchronisedLighting;
    }

    /**
     * Sets the value of the synchronisedLighting property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeYesNoType }{@code >}
     *     
     */
    public void setSynchronisedLighting(JAXBElement<CodeYesNoType> value) {
        this.synchronisedLighting = value;
    }

    public boolean isSetSynchronisedLighting() {
        return (this.synchronisedLighting!= null);
    }

    /**
     * Gets the value of the marker property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MarkerBeaconPropertyType }{@code >}
     *     
     */
    public JAXBElement<MarkerBeaconPropertyType> getMarker() {
        return marker;
    }

    /**
     * Sets the value of the marker property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MarkerBeaconPropertyType }{@code >}
     *     
     */
    public void setMarker(JAXBElement<MarkerBeaconPropertyType> value) {
        this.marker = value;
    }

    public boolean isSetMarker() {
        return (this.marker!= null);
    }

    /**
     * Gets the value of the part property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the part property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerticalStructurePartPropertyType }
     * 
     * 
     */
    public List<VerticalStructurePartPropertyType> getPart() {
        if (part == null) {
            part = new ArrayList<VerticalStructurePartPropertyType>();
        }
        return this.part;
    }

    public boolean isSetPart() {
        return ((this.part!= null)&&(!this.part.isEmpty()));
    }

    public void unsetPart() {
        this.part = null;
    }

    /**
     * Gets the value of the hostedPassengerService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostedPassengerService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostedPassengerService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PassengerServicePropertyType }
     * 
     * 
     */
    public List<PassengerServicePropertyType> getHostedPassengerService() {
        if (hostedPassengerService == null) {
            hostedPassengerService = new ArrayList<PassengerServicePropertyType>();
        }
        return this.hostedPassengerService;
    }

    public boolean isSetHostedPassengerService() {
        return ((this.hostedPassengerService!= null)&&(!this.hostedPassengerService.isEmpty()));
    }

    public void unsetHostedPassengerService() {
        this.hostedPassengerService = null;
    }

    /**
     * Gets the value of the supportedGroundLight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedGroundLight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedGroundLight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroundLightSystemPropertyType }
     * 
     * 
     */
    public List<GroundLightSystemPropertyType> getSupportedGroundLight() {
        if (supportedGroundLight == null) {
            supportedGroundLight = new ArrayList<GroundLightSystemPropertyType>();
        }
        return this.supportedGroundLight;
    }

    public boolean isSetSupportedGroundLight() {
        return ((this.supportedGroundLight!= null)&&(!this.supportedGroundLight.isEmpty()));
    }

    public void unsetSupportedGroundLight() {
        this.supportedGroundLight = null;
    }

    /**
     * Gets the value of the hostedNavaidEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostedNavaidEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostedNavaidEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NavaidEquipmentPropertyType }
     * 
     * 
     */
    public List<NavaidEquipmentPropertyType> getHostedNavaidEquipment() {
        if (hostedNavaidEquipment == null) {
            hostedNavaidEquipment = new ArrayList<NavaidEquipmentPropertyType>();
        }
        return this.hostedNavaidEquipment;
    }

    public boolean isSetHostedNavaidEquipment() {
        return ((this.hostedNavaidEquipment!= null)&&(!this.hostedNavaidEquipment.isEmpty()));
    }

    public void unsetHostedNavaidEquipment() {
        this.hostedNavaidEquipment = null;
    }

    /**
     * Gets the value of the hostedSpecialNavStation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostedSpecialNavStation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostedSpecialNavStation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialNavigationStationPropertyType }
     * 
     * 
     */
    public List<SpecialNavigationStationPropertyType> getHostedSpecialNavStation() {
        if (hostedSpecialNavStation == null) {
            hostedSpecialNavStation = new ArrayList<SpecialNavigationStationPropertyType>();
        }
        return this.hostedSpecialNavStation;
    }

    public boolean isSetHostedSpecialNavStation() {
        return ((this.hostedSpecialNavStation!= null)&&(!this.hostedSpecialNavStation.isEmpty()));
    }

    public void unsetHostedSpecialNavStation() {
        this.hostedSpecialNavStation = null;
    }

    /**
     * Gets the value of the hostedUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostedUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostedUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitPropertyType }
     * 
     * 
     */
    public List<UnitPropertyType> getHostedUnit() {
        if (hostedUnit == null) {
            hostedUnit = new ArrayList<UnitPropertyType>();
        }
        return this.hostedUnit;
    }

    public boolean isSetHostedUnit() {
        return ((this.hostedUnit!= null)&&(!this.hostedUnit.isEmpty()));
    }

    public void unsetHostedUnit() {
        this.hostedUnit = null;
    }

    /**
     * Gets the value of the hostedOrganisation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostedOrganisation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostedOrganisation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganisationAuthorityPropertyType }
     * 
     * 
     */
    public List<OrganisationAuthorityPropertyType> getHostedOrganisation() {
        if (hostedOrganisation == null) {
            hostedOrganisation = new ArrayList<OrganisationAuthorityPropertyType>();
        }
        return this.hostedOrganisation;
    }

    public boolean isSetHostedOrganisation() {
        return ((this.hostedOrganisation!= null)&&(!this.hostedOrganisation.isEmpty()));
    }

    public void unsetHostedOrganisation() {
        this.hostedOrganisation = null;
    }

    /**
     * Gets the value of the supportedService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServicePropertyType }
     * 
     * 
     */
    public List<ServicePropertyType> getSupportedService() {
        if (supportedService == null) {
            supportedService = new ArrayList<ServicePropertyType>();
        }
        return this.supportedService;
    }

    public boolean isSetSupportedService() {
        return ((this.supportedService!= null)&&(!this.supportedService.isEmpty()));
    }

    public void unsetSupportedService() {
        this.supportedService = null;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotePropertyType }
     * 
     * 
     */
    public List<NotePropertyType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<NotePropertyType>();
        }
        return this.annotation;
    }

    public boolean isSetAnnotation() {
        return ((this.annotation!= null)&&(!this.annotation.isEmpty()));
    }

    public void unsetAnnotation() {
        this.annotation = null;
    }

    /**
     * Gets the value of the lightingAvailability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lightingAvailability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLightingAvailability().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerticalStructureLightingStatusPropertyType }
     * 
     * 
     */
    public List<VerticalStructureLightingStatusPropertyType> getLightingAvailability() {
        if (lightingAvailability == null) {
            lightingAvailability = new ArrayList<VerticalStructureLightingStatusPropertyType>();
        }
        return this.lightingAvailability;
    }

    public boolean isSetLightingAvailability() {
        return ((this.lightingAvailability!= null)&&(!this.lightingAvailability.isEmpty()));
    }

    public void unsetLightingAvailability() {
        this.lightingAvailability = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerticalStructureTimeSliceType.Extension }
     * 
     * 
     */
    public List<VerticalStructureTimeSliceType.Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<VerticalStructureTimeSliceType.Extension>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.aixm.aero/schema/5.1}AbstractVerticalStructureExtension"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractVerticalStructureExtension"
    })
    public static class Extension {

        @XmlElementRef(name = "AbstractVerticalStructureExtension", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class)
        protected JAXBElement<? extends AbstractExtensionType> abstractVerticalStructureExtension;
        @XmlAttribute(name = "owns")
        protected Boolean owns;

        /**
         * Gets the value of the abstractVerticalStructureExtension property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link aero.aixm.extension.fns.VerticalStructureExtensionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link AbstractExtensionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link aero.aixm.event.VerticalStructureExtensionType }{@code >}
         *     
         */
        public JAXBElement<? extends AbstractExtensionType> getAbstractVerticalStructureExtension() {
            return abstractVerticalStructureExtension;
        }

        /**
         * Sets the value of the abstractVerticalStructureExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link aero.aixm.extension.fns.VerticalStructureExtensionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link AbstractExtensionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link aero.aixm.event.VerticalStructureExtensionType }{@code >}
         *     
         */
        public void setAbstractVerticalStructureExtension(JAXBElement<? extends AbstractExtensionType> value) {
            this.abstractVerticalStructureExtension = value;
        }

        public boolean isSetAbstractVerticalStructureExtension() {
            return (this.abstractVerticalStructureExtension!= null);
        }

        /**
         * Gets the value of the owns property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOwns() {
            if (owns == null) {
                return false;
            } else {
                return owns;
            }
        }

        /**
         * Sets the value of the owns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOwns(boolean value) {
            this.owns = value;
        }

        public boolean isSetOwns() {
            return (this.owns!= null);
        }

        public void unsetOwns() {
            this.owns = null;
        }

    }

}
