//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.04 at 11:05:52 AM EST 
//


package aero.aixm.extension.fns;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import aero.aixm.AbstractExtensionType;
import aero.aixm.ApronPropertyType;
import aero.aixm.RunwayPropertyType;
import aero.aixm.TaxiwayPropertyType;


/**
 * <p>Java class for TaxiwayExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxiwayExtensionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1}AbstractExtensionType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:us.gov.dot.faa.aim.fns}TaxiwayExtensionPropertyGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxiwayExtensionType", propOrder = {
    "intersectionsIntersectedByTaxiway",
    "intersectionsIntersectedByRunway",
    "intersectionsIntersectedByApron"
})
public class TaxiwayExtensionType
    extends AbstractExtensionType
{

    @XmlElement(name = "Intersections_intersectedByTaxiway", nillable = true)
    protected List<TaxiwayPropertyType> intersectionsIntersectedByTaxiway;
    @XmlElement(name = "Intersections_intersectedByRunway", nillable = true)
    protected List<RunwayPropertyType> intersectionsIntersectedByRunway;
    @XmlElement(name = "Intersections_intersectedByApron", nillable = true)
    protected List<ApronPropertyType> intersectionsIntersectedByApron;

    /**
     * Gets the value of the intersectionsIntersectedByTaxiway property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intersectionsIntersectedByTaxiway property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntersectionsIntersectedByTaxiway().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxiwayPropertyType }
     * 
     * 
     */
    public List<TaxiwayPropertyType> getIntersectionsIntersectedByTaxiway() {
        if (intersectionsIntersectedByTaxiway == null) {
            intersectionsIntersectedByTaxiway = new ArrayList<TaxiwayPropertyType>();
        }
        return this.intersectionsIntersectedByTaxiway;
    }

    /**
     * Gets the value of the intersectionsIntersectedByRunway property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intersectionsIntersectedByRunway property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntersectionsIntersectedByRunway().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RunwayPropertyType }
     * 
     * 
     */
    public List<RunwayPropertyType> getIntersectionsIntersectedByRunway() {
        if (intersectionsIntersectedByRunway == null) {
            intersectionsIntersectedByRunway = new ArrayList<RunwayPropertyType>();
        }
        return this.intersectionsIntersectedByRunway;
    }

    /**
     * Gets the value of the intersectionsIntersectedByApron property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intersectionsIntersectedByApron property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntersectionsIntersectedByApron().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApronPropertyType }
     * 
     * 
     */
    public List<ApronPropertyType> getIntersectionsIntersectedByApron() {
        if (intersectionsIntersectedByApron == null) {
            intersectionsIntersectedByApron = new ArrayList<ApronPropertyType>();
        }
        return this.intersectionsIntersectedByApron;
    }

}
