//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 07:41:16 AM EST 
//


package aero.aixm.extension.fns;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeMarkingStatusBaseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CodeMarkingStatusBaseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OBSC"/>
 *     &lt;enumeration value="PART_OBSC"/>
 *     &lt;enumeration value="FADED"/>
 *     &lt;enumeration value="REMOVED"/>
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="NON_STANDARD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CodeMarkingStatusBaseType")
@XmlEnum
public enum CodeMarkingStatusBaseType {

    OBSC,
    PART_OBSC,
    FADED,
    REMOVED,
    NONE,
    NON_STANDARD;

    public String value() {
        return name();
    }

    public static CodeMarkingStatusBaseType fromValue(String v) {
        return valueOf(v);
    }

}
