//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 07:41:16 AM EST 
//


package aero.aixm.extension.fns;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeNOTAMRequestActionBaseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CodeNOTAMRequestActionBaseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CREATE_NOTAM"/>
 *     &lt;enumeration value="CANCEL_NOTAM"/>
 *     &lt;enumeration value="CHECK_NOTAM_STATUS"/>
 *     &lt;enumeration value="CREATE_NOTAM_PREVIEW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CodeNOTAMRequestActionBaseType")
@XmlEnum
public enum CodeNOTAMRequestActionBaseType {

    CREATE_NOTAM,
    CANCEL_NOTAM,
    CHECK_NOTAM_STATUS,
    CREATE_NOTAM_PREVIEW;

    public String value() {
        return name();
    }

    public static CodeNOTAMRequestActionBaseType fromValue(String v) {
        return valueOf(v);
    }

}
